INSERT INTO encounter(soundeffects, difficultyToRun, isTown, fromAfar, locationDescription, name)
VALUES("246230__andreangelo__squelchy-mouth-cave-hq.wav", 12, false, "A large Cave mouth looming wide", "Stepping into a cave, you leave behind the outside world's brightness and warmth. \nAs your eyes adjust to the dim light, the temperature drops, and you feel a cool, damp air brushing against your skin. \nThe ground beneath your feet becomes uneven, and the echo of your footsteps fills the enclosed space. \nThe scent of earth and minerals lingers in the air, and the mysterious darkness ahead beckons you to explore further.", "cave");
INSERT INTO encounter(soundeffects, difficultyToRun, isTown, fromAfar, locationDescription, name)
VALUES("378209__felixblume__the-sounds-of-the-meadow-gran-sabana-venezuela.wav", 6, false, "A welcoming meadow, dotted with flowers and small plants", "Walking into a meadow, you step into a vast expanse of open space. \nSunlight bathes the area, warming your skin and brightening the surroundings. \nThe ground is covered with soft, knee-high grasses and wildflowers that sway gently in the breeze. \nThe air is filled with the scent of earth and blossoms. \nIn the distance, you might hear the chirping of birds or the buzzing of insects. \nIt's a peaceful and open landscape, inviting you to take in the natural beauty all around.", "meadow");
INSERT INTO encounter(soundeffects, difficultyToRun, isTown, fromAfar, locationDescription, name)
VALUES("135472__kvgarlic__summeropenfielddusk.wav", 5, false, "A field with rolling hills", "Walking into a field, you enter a spacious landscape with ground covered by short grasses and crops.\n Sunlight bathes the area, and the surroundings are open with a distant horizon or trees in the periphery. \nThe air carries the earthy scent of vegetation, and you can hear the rustling of leaves, \nthe chirping of birds, and the gentle swaying of plants in the wind.", "field");
INSERT INTO encounter(soundeffects, difficultyToRun, isTown, fromAfar, locationDescription, name)
VALUES("531724__klankbeeld__forest-summer-roond-021-200619_0186.wav", 10, false, "A Dense and gloomy forest", "Walking into a forest, you step into a dense and verdant environment. \nThe ground is covered with fallen leaves, twigs, and soft soil. \nTall trees rise around you, their branches forming a natural canopy overhead, dimming the light. \nThe air is cool, and the scent of earth and moss surrounds you. \nThe forest is alive with the chirping of birds, rustling of small animals, and the occasional crackling of branches. \nIt's a serene and mysterious realm, inviting you to explore its depths.", "forest");
INSERT INTO encounter(soundeffects, difficultyToRun, isTown, fromAfar, locationDescription, name)
VALUES("423119__ogsoundfx__medieval-city-sample.wav", 12, true, "A town peeking over the hills in the distance", "Walking into town narrow cobblestone streets wind between centuries-old stone buildings. \nOverhanging timber-framed houses line the lanes, and the air is filled with the scent of opportunity. \nThe town bustles with activity as villagers go about their daily routines. \nYou hear the clip-clop of horses' hooves, merchants haggling at market stalls, and the distant chime of a church bell.", "town");
INSERT INTO encounter(soundeffects, difficultyToRun, isTown, fromAfar, locationDescription, name)
VALUES("399744__inspectorj__ambience-florida-frogs-gathering-a.wav", 15, false, "What appears to be wetlands covered in fog", "As you step into the bog, the ground beneath your feet gives way, sinking into a squelchy, muddy morass. \nThe air is thick with a damp, earthy aroma, and the dense fog conceals much of the landscape. \nWaterlogged plants with twisted, moss-covered branches reach out from the murky waters, and the eerie chorus of croaking frogs and buzzing insects fills the air. \nYour every step is accompanied by a sucking sound as your boots struggle to break free from the mire, \nmaking each movement a slow and cautious endeavor in this eerie, desolate wetland.", "bog");
INSERT INTO encounter(soundeffects, difficultyToRun, isTown, fromAfar, locationDescription, name)
VALUES("543449__kostas17__howling-wind.wav", 6, false, "majestic mountain peaks disappearing into the clouds", "Walking up to a mountain is a gradual journey of ascending terrain. \nAs you approach the mountain, the landscape becomes steeper, and the air grows crisper. \nThe path typically leads through forests, meadows, or rocky trails, with each step offering a closer view of the majestic peak ahead. \nThe mountain looms larger and more imposing as you get nearer, and the anticipation of the climb ahead intensifies with each stride.", "mountain");
INSERT INTO encounter(soundeffects, difficultyToRun, isTown, fromAfar, locationDescription, name)
VALUES("584595__tosha73__mountain-river.wav", 6, false, "A river winding its way in the distance", "Approaching a river, you see the glistening water ahead. \nThe gentle sound of flowing water fills the air, and the earthy scent of the surrounding nature surrounds you. \nYou walk toward the riverbank, feeling the cool breeze and the soft, uneven ground underfoot. \nThe lush greenery and wildlife along the river's edge add to the tranquil atmosphere, making it a serene and inviting spot.", "river");
